#!/usr/bin/env bash
# scripts/reproduce_paper.sh
#
# One-shot reproduction script the manuscript's §7 Reproducibility
# commitments references. Runs everything that does NOT require Docker,
# LLM subscriptions, or the Ollama vision model -- i.e. proves the
# toolchain installs, the 6 injection primitives behave correctly, the
# 3 oracle implementations parse + score offline, all 6 LLM judges have
# their stubs wired up, the offline 12-PNG smoke runs end-to-end, and
# the W6 capture orchestrator wiring is healthy (dry-run plan).
#
# What this script does NOT do:
#   - Bring up any of the 8 docker-compose stacks (W6 real capture).
#   - Pull the Llama vision model (`ollama pull llama3.2-vision:11b`,
#     ~7 GB) needed for the Llama judge.
#   - Authenticate Claude OAuth / OpenAI Codex subscriptions for the
#     LLM-as-judge dispatcher (W7).
#   - Re-run the LLM dispatcher (requires subscriptions / API keys / Ollama).
#     The committed parquets in results/ are the data source for analysis.
#
# What this script DOES do for analysis (step 8): the Phase 1 analysis
# pipeline IS run against the committed parquets — pyarrow + pandas +
# numpy are auto-installed into .venv-analysis on first invocation. The
# headline κ + per-judge accuracy + per-category breakdown reproduced by
# the manuscript's §4 Results are regenerated by this step.
#
# To go from this dry run to the full ~11,200-judgment results.json:
#
#   # Pre-reqs (NOT done by this script):
#   docker --version                                  # Docker daemon up
#   ollama pull llama3.2-vision:11b                   # ~7 GB local
#   # ensure Claude OAuth + OpenAI Codex subscriptions are live
#
#   npx tsx scripts/capture_corpus.ts                 # 800 pairs (~3-5 h)
#   npx tsx scripts/capture_pairs_manifest.ts         # _pairs_manifest.json
#   npm run oracles:judge:dispatch -- --pairs data/images/_pairs_manifest.json
#
# Exit on first failure -- if anything breaks the rest of the pipeline
# can't be trusted, so we want loud failure.

set -euo pipefail
cd "$(dirname "$0")/.."

echo "==> [reproduce] 1/6 npm install"
npm install --no-audit --no-fund

echo "==> [reproduce] 2/6 playwright chromium (no-op if cached)"
npx playwright install chromium

echo "==> [reproduce] 3/6 unit tests for 6 injection primitives (offline)"
npm run test:primitives

echo "==> [reproduce] 4/6 unit tests for 3 oracles (offline: pixel + pHash + LLM stub)"
npm run test:oracles

echo "==> [reproduce] 5/7 LLM judge stubs (offline; no API calls)"
npm run test:llm_judges

echo "==> [reproduce] 6/7 Llama composite unit test (sharp side-by-side workaround)"
npm run test:llama_composite

echo "==> [reproduce] 7/8 offline 12-PNG end-to-end smoke (no docker)"
npx tsx tests/smoke_offline_pipeline.ts

echo "==> [reproduce] 8/8 Phase 1 analysis pipeline against committed parquets"
# Reproduces the headline κ + accuracy numbers in §4 of the manuscript from
# the two parquet files that ship in results/ (Phase 1 W7 dispatch +
# Llama re-run). No LLM subscription / Docker / Ollama required for this
# step — the parquets are already in the repo. Bootstrap seed 42, 1000
# resamples; output JSON + Markdown to analysis/results/phase1_analysis_<ts>.{json,md}.
if [ ! -d ".venv-analysis" ]; then
  echo "  Creating .venv-analysis (one-time setup)..."
  python3 -m venv .venv-analysis
  .venv-analysis/bin/pip install --quiet pyarrow pandas numpy requests
fi
.venv-analysis/bin/python3 analysis/analyze_judgments.py

echo
echo "==> [reproduce] OFFLINE SUITE + ANALYSIS PIPELINE PASSED"
echo "    Headline numbers reproduced; see analysis/results/phase1_analysis_<latest>.md"
echo
echo "Next steps (NOT performed here, require Docker + Ollama vision + subscriptions):"
echo "  npx tsx scripts/capture_corpus.ts --dry-run"
echo "    # prints per-app plan: which compose file, which seed cmd, point counts"
echo "  npx tsx scripts/capture_corpus.ts --offline-pipeline"
echo "    # captures 800 PNG pairs against synthetic HTML (no docker, no real apps)"
echo "    # proves the all-50-per-app capture loop + ledger pipeline works"
echo "  npx tsx scripts/capture_corpus.ts"
echo "    # REAL capture: brings up each docker-compose stack, seeds, captures 50,"
echo "    # tears down. Wall-clock: ~3-5 hours for 800 pairs across 8 apps."
echo "  npx tsx scripts/capture_pairs_manifest.ts"
echo "    # aggregates 8 per-app ledgers into data/images/_pairs_manifest.json"
echo "  npm run oracles:judge:dispatch -- --pairs data/images/_pairs_manifest.json"
echo "    # 6 judge wrappers exist (gpt4o, claude, claude-oauth, openai-codex,"
echo "    # gemini, llama). Default Phase 1 dispatch uses 3 subscription-path"
echo "    # judges (openai-codex + claude-oauth + llama) for \$0 cost."
echo "    # API-key variants available via --judges gpt4o,claude,gemini,llama."
echo "    # See oracles/llm_judge/dispatcher.ts for budget caps + concurrency."
echo "  .venv-analysis/bin/python3 analysis/analyze_judgments.py"
echo "    # Phase 1 analysis: pairwise Cohen's k + Fleiss' k + per-app +"
echo "    # per-category + accuracy vs ground-truth. Outputs to analysis/results/."
echo
echo "Real-app capture (W6) and judgment dispatch (W7) require:"
echo "  - Docker daemon running"
echo "  - ollama pull llama3.2-vision:11b   (~7 GB, required for Llama judge)"
echo "  - Claude OAuth + OpenAI Codex subscriptions active (or set API keys to"
echo "    use the gpt4o/claude API-key judges instead)"
echo "See scripts/capture_corpus.ts --help and oracles/llm_judge/dispatcher.ts --help"
echo "for full CLI."
